import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";

const inter_tight = Inter_Tight({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  authModal,
}: Readonly<{
  children: React.ReactNode;
  authModal: React.ReactNode;
}>) {
  

  return (
    <html lang="en">
      <body className={inter_tight.className}>

          <Navbar />
          <main
          // className="pt-[5.5rem]"
          >
            {children}
            {authModal}
          </main>
      </body>
    </html>
  );
}
